// @prepros-append "schedule.js"
// @prepros-append "lessonTime.js"
// @prepros-append "date.js"
// @prepros-append "tabs.js"
// @prepros-append "fullLessonName.js"
// @prepros-append "lectionsPractice.js"
// @prepros-append "remain.js"
// @prepros-append "now.js"